config/routes.rb
Rails.application.routes.draw do
  resources :user_place_lists
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/idea_bubbles' => 'static_pages#idea_bubbles', :as => :idea_bubbles
  get 'static_pages/travel_tracker' => 'static_pages#travel_tracker', :as => :travel_tracker
  resources :ideas
end

app/models/user_place_list.rb
class UserPlaceList < ActiveRecord::Base
  belongs_to :user
end

app/controllers/user_place_lists_controller.rb
class UserPlaceListsController < ApplicationController
  before_action :set_user_place_list, only: [:show, :edit, :update, :destroy]

  # GET /user_place_lists
  # GET /user_place_lists.json
  def index
    @user_place_lists = UserPlaceList.all
  end

  # GET /user_place_lists/1
  # GET /user_place_lists/1.json
  def show
  end

  # GET /user_place_lists/new
  def new
    @user_place_list = UserPlaceList.new
  end

  # GET /user_place_lists/1/edit
  def edit
  end

  # POST /user_place_lists
  # POST /user_place_lists.json
  def create
    @user_place_list = UserPlaceList.new(user_place_list_params)

    respond_to do |format|
      if @user_place_list.save
        format.html { redirect_to @user_place_list, notice: 'User place list was successfully created.' }
        format.json { render :show, status: :created, location: @user_place_list }
      else
        format.html { render :new }
        format.json { render json: @user_place_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_place_lists/1
  # PATCH/PUT /user_place_lists/1.json
  def update
    respond_to do |format|
      if @user_place_list.update(user_place_list_params)
        format.html { redirect_to @user_place_list, notice: 'User place list was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_place_list }
      else
        format.html { render :edit }
        format.json { render json: @user_place_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_place_lists/1
  # DELETE /user_place_lists/1.json
  def destroy
    @user_place_list.destroy
    respond_to do |format|
      format.html { redirect_to user_place_lists_url, notice: 'User place list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_place_list
      @user_place_list = UserPlaceList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_place_list_params
      params.fetch(:user_place_list, {})
    end
end

app/helpers/user_place_lists_helper.rb
module UserPlaceListsHelper
end

app/views/user_place_lists/_form.html.erb
<%= form_for(@user_place_list) do |f| %>
  <% if @user_place_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_place_list.errors.count, "error") %> prohibited this user_place_list from being saved:</h2>

      <ul>
      <% @user_place_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_place_lists/edit.html.erb
<h1>Editing User Place List</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_place_list %> |
<%= link_to 'Back', user_place_lists_path %>

app/views/user_place_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Place Lists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_place_lists.each do |user_place_list| %>
      <tr>
        <td><%= link_to 'Show', user_place_list %></td>
        <td><%= link_to 'Edit', edit_user_place_list_path(user_place_list) %></td>
        <td><%= link_to 'Destroy', user_place_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User place list', new_user_place_list_path %>

app/views/user_place_lists/new.html.erb
<h1>New User Place List</h1>

<%= render 'form' %>

<%= link_to 'Back', user_place_lists_path %>

app/views/user_place_lists/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_place_list_path(@user_place_list) %> |
<%= link_to 'Back', user_place_lists_path %>